module PythonHS.Lexer.TokenType (TokenType (..)) where

data TokenType
  = IdentifierToken
  | IntegerToken
  | FloatToken
  | StringToken
  | AssignToken
  | PlusAssignToken
  | MinusAssignToken
  | StarAssignToken
  | SlashAssignToken
  | PercentAssignToken
  | DoubleSlashAssignToken
  | PlusToken
  | MinusToken
  | StarToken
  | SlashToken
  | DoubleSlashToken
  | PercentToken
  | LParenToken
  | RParenToken
  | LBracketToken
  | RBracketToken
  | LBraceToken
  | RBraceToken
  | ColonToken
  | CommaToken
  | DotToken
  | NewlineToken
  | IndentToken
  | DedentToken
  | PrintToken
  | IfToken
  | ElifToken
  | TrueToken
  | FalseToken
  | NoneToken
  | ElseToken
  | WhileToken
  | ForToken
  | InToken
  | DefToken
  | ReturnToken
  | BreakToken
  | ContinueToken
  | GlobalToken
  | PassToken
  | FromToken
  | AsToken
  | ImportToken
  | EqToken
  | NotEqToken
  | LtToken
  | GtToken
  | LteToken
  | GteToken
  | AndToken
  | OrToken
  | NotToken
  | EOFToken
  deriving (Eq, Show)
